
services:
  mysql:
    image: bitnami/mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=my_password
      - MYSQL_DATABASE=metastore
    mem_limit: 512m
    networks:
      - spark_net

  hive-metastore:
    image: apache/hive:4.0.1
#    image: bitnami/hive:latest
    container_name: hive-metastore
    environment:
      - HIVE_MODE=metastore
      - HIVE_METASTORE_PORT_NUMBER=9083
      - HIVE_METASTORE_HOSTNAME=hive-metastore
      - HIVE_DATABASE_HOST=mysql
      - HIVE_DATABASE_USER=root
      - HIVE_DATABASE_PASSWORD=my_password
      - HIVE_DATABASE_NAME=metastore
    depends_on:
      - mysql
    mem_limit: 512m
    ports:
      - "9083:9083"
    networks:
      - spark_net

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9090"
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - ./data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    mem_limit: 512m
    networks:
      - spark_net

  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_NO_DAEMONIZE=true
      # Habilita event log para History Server
      - SPARK_EVENTLOG_ENABLED=true
      - SPARK_EVENTLOG_DIR=file:///tmp/spark-events
      - SPARK_SQL_CATALOG_IMPLEMENTATION=hive
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./spark-events:/tmp/spark-events
      - ./hive-site.xml:/opt/bitnami/spark/conf/hive-site.xml
    mem_limit: 512m
    networks:
      - spark_net

  spark-worker-1:
    image: bitnami/spark:latest
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=512m
      - SPARK_WORKER_CORES=1
      - SPARK_NO_DAEMONIZE=true
      - SPARK_SQL_CATALOG_IMPLEMENTATION=hive
    depends_on:
      - spark-master
    volumes:
      - ./hive-site.xml:/opt/bitnami/spark/conf/hive-site.xml
    mem_limit: 512m
    networks:
      - spark_net

  spark-worker-2:
    image: bitnami/spark:latest
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=512m
      - SPARK_WORKER_CORES=1
      - SPARK_NO_DAEMONIZE=true
      - SPARK_SQL_CATALOG_IMPLEMENTATION=hive
    depends_on:
      - spark-master
    volumes:
      - ./hive-site.xml:/opt/bitnami/spark/conf/hive-site.xml
    mem_limit: 512m
    networks:
      - spark_net

  spark-history-server:
    image: bitnami/spark:latest
    container_name: spark-history-server
    environment:
      - SPARK_MODE=history-server
      - SPARK_HISTORY_SERVER_OPTS=--dir /tmp/spark-events
      - SPARK_NO_DAEMONIZE=true
      - SPARK_SQL_CATALOG_IMPLEMENTATION=hive
    depends_on:
      - spark-master
    volumes:
      - ./spark-events:/tmp/spark-events
      - ./hive-site.xml:/opt/bitnami/spark/conf/hive-site.xml
    ports:
      - "18080:18080"
    mem_limit: 512m
    networks:
      - spark_net

networks:
  spark_net:
    driver: bridge
